/*
-- Query: select * from rapiddev.itemsmetadata
LIMIT 0, 1000

-- Date: 2020-07-08 11:02
*/
/*
-- Query: select * from rapiddev.itemsmetadata
LIMIT 0, 1000

-- Date: 2020-08-06 23:26
*/
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Address','addressConverter','de.hybris.platform.commercefacades.user.data',NULL,NULL,'de.hybris.platform.core.model.user','addressService','de.hybris.platform.servicelayer.user','addressReverseConverter',0,'AddressData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('BaseStore','baseStoreConverter','de.hybris.platform.commercefacades.basestore.data',NULL,NULL,'de.hybris.platform.store','baseStoreService','de.hybris.platform.store.services',NULL,0,'BaseStoreData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Cart','cartConverter','de.hybris.platform.commercefacades.order.data',NULL,NULL,'de.hybris.platform.core.model.order','cartService','de.hybris.platform.order',NULL,0,'CartData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('CartEntry',NULL,NULL,NULL,NULL,'de.hybris.platform.core.model.order','cartEntryService','de.hybris.platform.order',NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Category','categoryConverter','de.hybris.platform.commercefacades.product.data',NULL,NULL,'de.hybris.platform.category.model','categoryService','de.hybris.platform.category',NULL,0,'CategoryData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('CMSSite',NULL,NULL,NULL,NULL,'de.hybris.platform.cms2.model.site','cmsSiteService','de.hybris.platform.cms2.servicelayer.services',NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Consignment','consignmentConverter','de.hybris.platform.commercefacades.order.data',NULL,NULL,'de.hybris.platform.ordersplitting.model','consignmentService','de.hybris.platform.ordersplitting',NULL,0,'ConsignmentData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('ConsignmentEntry',NULL,'de.hybris.platform.commercefacades.order.data',NULL,NULL,'de.hybris.platform.ordersplitting.model',NULL,NULL,NULL,0,'ConsignmentEntryData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('CronJob',NULL,NULL,NULL,NULL,'de.hybris.platform.cronjob.model','cronJobService','de.hybris.platform.servicelayer.cronjob',NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('CsTicket','ticketConverter','de.hybris.platform.customerticketingfacades.data',NULL,NULL,'de.hybris.platform.ticket.model','ticketService','de.hybris.platform.ticket.service',NULL,0,'TicketData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Currency','currencyConverter','de.hybris.platform.commercefacades.storesession.data',NULL,NULL,'de.hybris.platform.core.model.c2l',NULL,NULL,NULL,0,'CurrencyData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Customer','customerConverter','de.hybris.platform.commercefacades.user.data',NULL,NULL,'de.hybris.platform.core.model.user','userService','de.hybris.platform.servicelayer.user','customerReverseConverter',0,'CustomerData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('DiscountRow',NULL,NULL,NULL,NULL,'de.hybris.platform.europe1.model',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Employee',NULL,NULL,NULL,NULL,'de.hybris.platform.core.model.user',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Language','languageConverter','de.hybris.platform.commercefacades.storesession.data',NULL,NULL,'de.hybris.platform.core.model.c2l',NULL,NULL,NULL,0,'LanguageData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Media','mediaModelConverter','de.hybris.platform.cmsfacades.data','','','de.hybris.platform.core.model.media','mediaService','de.hybris.platform.servicelayer.media',NULL,0,'MediaData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('MediaContainer',NULL,'de.hybris.platform.cmsfacades.data',NULL,NULL,'de.hybris.platform.core.model.media','mediaContainerService','de.hybris.platform.servicelayer.media',NULL,0,'MediaContainerData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('MediaFolder',NULL,NULL,NULL,NULL,'de.hybris.platform.core.model.media',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Order','orderConverter','de.hybris.platform.commercefacades.order.data',NULL,NULL,'de.hybris.platform.core.model.order','orderService','de.hybris.platform.order',NULL,0,'OrderData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('OrderEntry','orderEntryConverter','de.hybris.platform.commercefacades.order.data',NULL,NULL,'de.hybris.platform.core.model.order','orderEntryService','de.hybris.platform.order',NULL,0,'OrderEntryData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('PaymentInfo',NULL,'de.hybris.platform.acceleratorservices.payment.data',NULL,NULL,'de.hybris.platform.core.model.order.payment','paymentInfoService','de.hybris.platform.order',NULL,0,'PaymentInfoData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('PointOfService','pointOfServiceConverter','de.hybris.platform.commercefacades.storelocator.data',NULL,NULL,'de.hybris.platform.storelocator.model','pointOfServiceService','de.hybris.platform.storelocator.pos',NULL,0,'PointOfServiceData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('PriceRow',NULL,NULL,NULL,NULL,'de.hybris.platform.europe1.model',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Product','productConverter','de.hybris.platform.commercefacades.product.data',NULL,NULL,'de.hybris.platform.core.model.product','productService','de.hybris.platform.product',NULL,0,'ProductData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('ProductReference','productReferenceConverter','de.hybris.platform.commercefacades.product.data',NULL,NULL,'de.hybris.platform.catalog.model','productReferenceService','de.hybris.platform.catalog.references',NULL,0,'ProductReferenceData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('PromotionGroup','promotionsConverter','de.hybris.platform.commercefacades.product.data',NULL,NULL,'de.hybris.platform.promotions.model','promotionsService','de.hybris.platform.promotions',NULL,0,'PromotionData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Region','regionConverter','de.hybris.platform.commercefacades.user.data',NULL,NULL,'de.hybris.platform.core.model.c2l',NULL,NULL,NULL,0,'RegionData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('ReturnOrder',NULL,NULL,NULL,NULL,'de.hybris.platform.returns.model',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('ReturnOrderEntry',NULL,NULL,NULL,NULL,'de.hybris.platform.returns.model',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('StockLevel','stockConverter','de.hybris.platform.commercefacades.product.data',NULL,NULL,'de.hybris.platform.ordersplitting.model','stockService','de.hybris.platform.stock',NULL,0,'StockData');
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('UserGroup',NULL,NULL,NULL,NULL,'de.hybris.platform.core.model.user',NULL,NULL,NULL,0,NULL);
INSERT INTO 'rapiddev.itemsmetadata' (`itemmodelname`,`converter`,`dtopackage`,`extensionname`,`formname`,`modelpackage`,`servicename`,`servicepackage`,`reverseconverter`,`enum`,`dtoname`) VALUES ('Warehouse',NULL,NULL,NULL,NULL,'de.hybris.platform.ordersplitting.model','warehouseService','de.hybris.platform.ordersplitting',NULL,0,NULL);

